# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Anuraag Kansara
title: Masters Student at IIT Kanpur
email: kansara@iitk.ac.in
phone: (+91) 772-780-9811

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  anuraagkansara
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: avi_kansara
linkedin_username: anuraagkansara
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Anuraag and I'm a Final year Postgraduate student at Indian Institute of Technology, Kanpur.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in ...... some of my other interests and hobbies are:
   - Photography
#   - Cricket
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
